---
title: "Fire_Maps"
author: "Alex Honeyman"
date: "4/21/2021"
output: html_document
---

#####################
# Fire maps #########
#####################
#**NOTE: To avoid package dependency / version interference issues, this notebook should be run in a fresh RStudio session.

#Getting individual plot lat. and long. for mapping study sites.
```{r}
library(phyloseq)
library(dplyr)

fire_ps <- readRDS("/Users/alexhoneyman/Documents/MICROBES_ARE_HUNGRY/Data and Code for Projects/fire_1_051421_2/Final_phyloseq/fire_ps.rds")

#416 Fire 2018 sites
temp <- data.frame(sample_data(fire_ps))
temp1 <- subset(temp, (temp$fire == "416 Fire") & (temp$time_point == "1") & (temp$depth_group == "1"))
temp2 <- distinct(temp1, latitude, longitude)
F416_2018_sites <- data.frame(temp2[1:7,])

#416 Fire 2019-2020 sites
temp <- data.frame(sample_data(fire_ps))
temp1 <- subset(temp, (temp$fire == "416 Fire") & (temp$time_point == "2") & (temp$depth_group == "1"))
F416_2019_2020_sites <- data.frame(distinct(temp1, latitude, longitude))

#Decker Fire All sites
temp <- data.frame(sample_data(fire_ps))
temp1 <- subset(temp, (temp$fire == "Decker Fire") & (temp$time_point == "1"))
temp2 <- distinct(temp1, latitude, longitude)
Decker_all_sites <- data.frame(temp2[2:31,])

###Making sure lat. and long. are numeric.
#416 Fire 2018
F416_2018_sites$latitude <- as.numeric(F416_2018_sites$latitude)
F416_2018_sites$longitude <- as.numeric(F416_2018_sites$longitude)
F416_2018_sites <- data.frame(F416_2018_sites)
#416 Fire 2019-2020
F416_2019_2020_sites$latitude <- as.numeric(F416_2019_2020_sites$latitude)
F416_2019_2020_sites$longitude <- as.numeric(F416_2019_2020_sites$longitude)
F416_2019_2020_sites <- data.frame(F416_2019_2020_sites)
#Decker Fire all times
Decker_all_sites$latitude <- as.numeric(Decker_all_sites$latitude)
Decker_all_sites$longitude <- as.numeric(Decker_all_sites$longitude)
Decker_all_sites <- data.frame(Decker_all_sites)


```

#Making the maps.
```{r}

#Libraries.
library("ggplot2")
library("sf")
library("maps")
library("tools")
library("rnaturalearth")
library("rnaturalearthdata")
library("ggmap")
library(ggspatial)
library(GISTools)
library(ggsn)
library(mapproj)

#Gather world and state data.
world <- ne_countries(scale = "medium", returnclass = "sf")
states <- st_as_sf(map("state", plot = FALSE, fill = TRUE)) #Get state data.
states <- cbind(states, st_coordinates(st_centroid(states))) #Determine the centroids of states for labeling.
states$ID <- toTitleCase(states$ID) #Allowing capitalization for the states.

##### Uncomment the block of code below to download the Google maps from online, but the maps we need have already been saved to the computer and are imported with the next code block. ##############
# #Need to link R to one's Google API.
# #This is a private key linked to one's Google Account with charge privileges! Be sure to keep secure like a credit card. Should change the API key with Google occasionally.
# register_google(key = "XXXXXXXXXXXXXX") #One can find their API key in their Google Cloud account.
# #Download maps with the Google API.
# map_hermosa <- get_googlemap("Hermosa, Colorado", zoom = 10, maptype = "terrain")
# map_howard <- get_googlemap("Howard, Colorado", zoom = 11, maptype = "terrain")
# #Save the Google Maps so we don't have to download them everytime.
# saveRDS(map_hermosa, file = "/Users/alexhoneyman/Documents/MICROBES_ARE_HUNGRY/Data and Code for Projects/fire_1_051421_2/maps_data/Google_maps/map_hermosa")
# saveRDS(map_howard, file = "/Users/alexhoneyman/Documents/MICROBES_ARE_HUNGRY/Data and Code for Projects/fire_1_051421_2/maps_data/Google_maps/map_howard")

#Read in the Google Maps from computer.
map_hermosa <- readRDS(file = "/Users/alexhoneyman/Documents/MICROBES_ARE_HUNGRY/Data and Code for Projects/fire_1_051421_2/maps_data/Google_maps/map_hermosa")
map_howard <- readRDS(file = "/Users/alexhoneyman/Documents/MICROBES_ARE_HUNGRY/Data and Code for Projects/fire_1_051421_2/maps_data/Google_maps/map_howard")

#Fire boundary shape files. Fire maps were first viewed in Google Earth using .KMZ files from the National Weather Service (Decker Fire), and the Monitoring Trends in Burn Severity Database (416 Fire); then, individual fire boundary .kml files were exported / saved. The .kml files are what we import here.
F416_boundary <- st_read("/Users/alexhoneyman/Documents/MICROBES_ARE_HUNGRY/Data and Code for Projects/fire_1_051421_2/maps_data/416Fire_perimeter.kml")
Decker_boundary <- st_read("/Users/alexhoneyman/Documents/MICROBES_ARE_HUNGRY/Data and Code for Projects/fire_1_051421_2/maps_data/Decker_perimeter.kml")

#Moving the state label a little.
states$nudge_y <- +1

#Colorado overview map.
ggplot(data = world) +
    geom_sf(fill = "antiquewhite1") +
    geom_sf(data = states, fill = NA) + 
    geom_sf(data = F416_boundary) +
    geom_sf(data = Decker_boundary) +
    geom_label(data = states, aes(X, Y, label = ID), size = 5, fontface = "bold", nudge_y = states$nudge_y) +
    coord_sf(xlim = c(-110, -103), ylim = c(36.3, 41), expand = FALSE) +
    annotation_scale(location = "br", width_hint = 0.5) +
    annotation_north_arrow(location = "br", which_north = "true", 
        pad_x = unit(0.75, "in"), pad_y = unit(0.5, "in"),
        style = north_arrow_fancy_orienteering)

#Transform the fire boundary shapefiles to EPSG 3857 (Pseudo-Mercator, what Google uses)
F416_boundary_3857 <- st_transform(F416_boundary, 3857)
Decker_boundary_3857 <- st_transform(Decker_boundary, 3857)

# Define a function to fix the bbox to be in EPSG:3857. Essentially, we need to make sure that the shape files and the underlying topo map are using the same coordinate system / units.
ggmap_bbox <- function(map) {
  if (!inherits(map, "ggmap")) stop("map must be a ggmap object")
  # Extract the bounding box (in lat/lon) from the ggmap to a numeric vector, 
  # and set the names to what sf::st_bbox expects:
  map_bbox <- setNames(unlist(attr(map, "bb")), 
                       c("ymin", "xmin", "ymax", "xmax"))

  # Coonvert the bbox to an sf polygon, transform it to 3857, 
  # and convert back to a bbox (convoluted, but it works)
  bbox_3857 <- st_bbox(st_transform(st_as_sfc(st_bbox(map_bbox, crs = 4326)), 3857))

  # Overwrite the bbox of the ggmap object with the transformed coordinates 
  attr(map, "bb")$ll.lat <- bbox_3857["ymin"]
  attr(map, "bb")$ll.lon <- bbox_3857["xmin"]
  attr(map, "bb")$ur.lat <- bbox_3857["ymax"]
  attr(map, "bb")$ur.lon <- bbox_3857["xmax"]
  map
}

# Use the function to convert topo maps to the right units and coordinates:
map_hermosa_convert <- ggmap_bbox(map_hermosa)
map_howard_convert <- ggmap_bbox(map_howard)

#416 Fire topo inset map.
ggmap(map_hermosa_convert) + 
  coord_sf(crs = st_crs(3857)) + # force the ggplot2 map to be in 3857
  geom_sf(data = F416_boundary_3857, inherit.aes = FALSE, aes(fill = "red")) +
  theme(legend.position = "none")
#Decker Fire topo inset map.
ggmap(map_howard_convert) + 
  coord_sf(crs = st_crs(3857)) + # force the ggplot2 map to be in 3857
  geom_sf(data = Decker_boundary_3857, inherit.aes = FALSE, aes(fill = "red")) +
  theme(legend.position = "none")

#416 Fire detail plot map.
ggplot() + 
  geom_sf(data = F416_boundary, fill = "gray") +
  annotation_scale(location = "bl", width_hint = 0.5) +
  annotation_north_arrow(location = "tr", which_north = "true", 
        pad_x = unit(0, "in"), pad_y = unit(0.2, "in"),
        style = north_arrow_fancy_orienteering) +
  geom_point(data=F416_2019_2020_sites, aes(x=longitude, y=latitude), color="red") +
  coord_sf(xlim = c(-107.9, -107.8),ylim = c(37.45, 37.55))
#Decker Fire detail plot map.
ggplot() + 
  geom_sf(data = Decker_boundary, fill = "gray") +
  annotation_scale(location = "bl", width_hint = 0.5) +
  annotation_north_arrow(location = "tl", which_north = "true", 
        pad_x = unit(1, "in"), pad_y = unit(0.2, "in"),
        style = north_arrow_fancy_orienteering) +
  geom_point(data=Decker_all_sites, aes(x=longitude, y=latitude), color="red") +
  coord_sf(xlim = c(-105.98, -105.95),ylim = c(38.450, 38.467))

####Export dimensions (inches):
#CO_overview: 6x8
#416_inset: 6x8
#Decker_inset: 6x8
#416_plots_detail: 6x8
#Decker_plots_detail: 6x8


```
